// client/src/lib/components/Post.svelte
<script>
    export let avatar = "./avatar.png";
    export let id = "ID";
    export let nick = "Vaybe";
    export let sage = true;
    export let message = "text here";
    export let date = "Date";
    export let postNumber = 0;
</script>

<div class="flex space-x-4 m-2 items-start">
    <img src={avatar} alt="avatar" class="h-20 rounded-xl shadow-xl" />

    <div
        class="flex-1 p-2 rounded-xl shadow-xl relative speech-bubble
               {postNumber % 3 === 0
            ? 'bg-green-100 bubble-color-0'
            : postNumber % 3 === 1
              ? 'bg-blue-100 bubble-color-1'
              : 'bg-purple-200 bubble-color-2'}"
    >
        <div
            class="flex items-center space-x-3 text-xs sm:text-sm text-gray-800"
        >
            <span>{postNumber}</span>
            <a href="/p/{id}" class="text-black hover:text-blue-500 mx-4"
                >{nick}</a
            >
            {#if sage}
                <span class="text-gray-500">[sage]</span>
            {/if}
            <span class="ml-auto font-mono text-[10px] sm:text-xs">{id}</span>
        </div>

        <div class="text-black text-sm sm:text-base break-words break-all">
            {message}
        </div>

        <div class="text-[10px] sm:text-xs text-gray-400 mt-1 text-right">
            {date}
        </div>
    </div>
</div>

<style>
    .speech-bubble::before {
        content: "";
        position: absolute;
        left: -15px;
        top: 40px;
        border-top: 10px solid transparent;
        border-bottom: 10px solid transparent;
        border-right-width: 15px;
        transform: skewY(50deg);
    }

    .bubble-color-0::before {
        border-right-color: rgba(220, 252, 231, 1);
    }
    .bubble-color-1::before {
        border-right-color: rgba(219, 234, 254, 1);
    }
    .bubble-color-2::before {
        border-right-color: rgba(233, 213, 255, 1);
    }
</style>

// client/src/components/Post/index.jsx
import defaultAvatar1 from '~/components/Post/avatar1.png';
import defaultAvatar2 from '~/components/Post/avatar2.png';
import defaultAvatar3 from '~/components/Post/avatar3.png';
import '~/components/Post/index.css';

export default function PostBubble({
  name = 'USERNAME',
  ID = 'ID',
  avatar, 
  text = 'Message Text!!!',
  postNumber = 0,
  sage = true,
  date = 'DATE',
}) {
  const bubbleColor =
    postNumber % 3 === 0
      ? 'bg-green-100 bubble-color-0'
      : postNumber % 3 === 1
      ? 'bg-blue-100 bubble-color-1'
      : 'bg-purple-200 bubble-color-2';

  const avatarByColor =
    postNumber % 3 === 0
      ? defaultAvatar1
      : postNumber % 3 === 1
      ? defaultAvatar2
      : defaultAvatar3;
  const finalAvatar = avatar || avatarByColor;

  return (
    <div className="flex space-x-2 m-2 items-start sm:space-x-4">
      <img
        src={finalAvatar}
        alt="avatar"
        className="h-18 w-18 sm:h-22 sm:w-22 rounded-lg sm:rounded-xl"
      />
      <div
        className={`flex-1 p-2 px-3 rounded-[14px] relative speech-bubble ${bubbleColor}`}
      >
        <div className="flex items-center space-x-5 text-xs sm:text-sm">
          <span className="text-gray-500">{postNumber}</span>
          <a href={`/p/${ID}`} className="hover:text-blue-500 font-medium">
            {name}
          </a>
          {sage && (
            <span className="text-black text-xs sm:text-sm">[sage]</span>
          )}
          <span className="ml-auto font-mono text-[9px] sm:text-xs text-gray-500">
            {ID}
          </span>
        </div>
        <div className="text-sm sm:text-base break-words break-all mt-1">
          {text}
        </div>
        <div className="text-[9px] sm:text-xs mt-1 text-right text-gray-600">
          {date}
        </div>
      </div>
    </div>
  );
}
